apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:omlmOTv7soXZQq//RY6tUP95TbgnDrjmDzuJYcWP2f7ob3iYWnzLMdBWzCW9+gDZoiJQ48qyy2Xp0FYLlw074qjkp1yKktgAsyNQnoBI05ZU+CcpkNZ3AUR6odh6e0g0yIX0UwMCnbYWCyQGLo5vPl5JmbkiRvkhzCmkQ9zfUE1mDt8EhC0/jNDbD2iyOBHwQXPdKvRmKLx0rbaGiNbHVQNgamqpwsmIDenw8KOGDLlDe9fZ4FoxQr/GklGzV1EC7bkmY5Q1P58JcB7/y5d6NzjTeanoy1CzUhjrb65/tel1QkgZjow0fiJMqFA=,iv:62WPWrQfUNKovXxdFyK7QGSX4gMyxW0w71qFi2h3Pww=,tag:Whv6zDv0Elppvjt22ucDnw==,type:str]
kind: Secret
metadata:
    name: abs
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTXRtZ0hqbzVCRzhWZjht
            aUVjWGIrYkRoTmV0SG5pM2FRa2o3aWxWcmpjCjlCQXVTNG9aeEJHMjdKZ2IyNzBx
            ZHlVUm5oUU9jMGc0dVNmMVNaQjRjVVkKLS0tIEM2SGVLcDVrN2dCS3JhSFZUc1V3
            SytYTGc4WGFoMGJkc1lTamU3UldjcWMKa7zxdU1XvlbGrjgg8Pd+OiDZKrwbLNAt
            i4Tjwyk0/NAJKXv7hlDOEXP5+7kYwuKQaeGYs6vaJ9WWf+8n5rJVIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ly7h0vwxqjxffe78l3gp00lzue9g6m4w5w22e394q98umdk6wvxsynguxt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T14:48:32Z"
    mac: ENC[AES256_GCM,data:xIg05tPimt993e+L1fjbyj5aCUAOEYnZKakl+zJkAUzh6BsDhdNSl8maAqlpDgF9Dr79uZL1kUKjFvtgffAOmnyVdZsbATsT2ly+G5Vv6zg7L1RprXDijwN9ZsssDtsdPh0lOzrMGoYqyy5AlUBoVM9Ys8wRJFXtdaHOXjzBJA4=,iv:JegZDh8FPn+9QSmpqufqcPWAfkbpZqoHjH17bB7SI2w=,tag:087Fnjg7EqMbo/0ynq/uEg==,type:str]
    version: 3.13.1
