apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobs
  template:
    metadata:
      labels:
        app: audiobs
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          envFrom:
            - configMapRef:
                name: abs-config
          ports:
          - containerPort: 13378

            volumeMounts:
            - mountPath: /app/config
              name: audiobs-data-pvc
              subPath: config

            - mountPath: /app/metadata
              name: audiobs-data-pvc
              subPath: metadata

      volumes:
        - name: audiobs-data-pvc
          persistentVolumeClaim:
            claimName: audiobs-data-pvc
