apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobs
  template:
    metadata:
      labels:
        app: audiobs
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
          - containerPort: 13378:80

#            volumeMounts:
#            - mountPath: /app/config
#              name: audiobs-data-pvc
#
#              mountPath: /app/metadata
#              name: audiobs-data-pvc

#      volumes:
#        - name: audiobs-data-pvc
#          persistentVolumeClaim:
#            claimName: audiobs-data-pvc



