apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:cosan1IDhLlJaAo1ENPRwwmTOze87g6n1QxSpdRYA5SwlSaseBbLhlAjQD667L3fOTDPFafyH7G6aD9Yao4ldVEPfPLgzqs+D7kEHouBv35Ndtx6ecxONt/t5PqyFQCW4/AGrPZXQrN+gayecUE2Er5as8r8Xmkmj+t20pX4X/R7TcIu/AbpnRDbGSC2+/e76faQhU0hnrwmlYRV8VW+BiuNbtANscH3oD5QSVtToKT25I7e1eDiJu3mxErSjlApdl0ZbPYq7FomnPKHzhWDuVLhMTXFgppRmD2PKOock8EfkhJe4CLnu6jU0NE=,iv:cbLf3m/QsRoiqO2GKu6XmbMftj/XCaAoKZLpp2IKF+s=,tag:xfNfCe6iBqelvt8TAeBV/A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKckhnNW9JeEJRS3JBSVhv
            WDdwWVU3ZFZVKyt1TkVuRFlaY1pNaWlSNzNzClg3bzcza0IxbWwrN2l6M1M1Mytj
            NWljZ3RUazNtQWZkVDA3WDNjbHpzdDgKLS0tIHNTa3VWVUVhSVpFZjZZWDJwSHdO
            Z0pyNkhrZGFwNTd6eXA1SGNVc052MjQKaGLJXo5yWZeJqkmv5EVHvUuvLo4nIHxv
            9gDlBUe6AFwJXvNBqPO9MBQhISWZaya8YO3S7qxPRcoz5nVkclC6Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ly7h0vwxqjxffe78l3gp00lzue9g6m4w5w22e394q98umdk6wvxsynguxt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T15:53:52Z"
    mac: ENC[AES256_GCM,data:QDKpYUQosZzQpq0qV+t2OpoWm99zLZtnhdMArt4kmQk+hJaVR91bKLeI8kHQwarUP9weSLY2owzauqcQ7izE+LnnBsbfzAQWN4CK4BSaipKvfnUuhsNabUDSAkYntWG3UC/gvzLV6zo1Dc7zpmCMCZqZfzn7g9vLqdP0E7fK1zY=,iv:/tdwe+6FbXbf/7MLSlYxmSZ7TbKSMtdEdpowFNsSZVs=,tag:kU1m1HqF3nXI01TJeOR8LQ==,type:str]
    version: 3.13.1
