apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:e9BzCRMk1Hk=,iv:Foq0ph5ysTbLXTiKgvL8s6oplaC9VCx2Ojb9WI8Wcc0=,tag:MGq/VdKXm+IX4BxDZFta3w==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:UT2P2NLyopJ8xBHzmtN+ggduuZw=,iv:bo9v0n07Tu523kK/vbziQVeEvb3MF2hg+U4fvWpxaNk=,tag:BK0vTEKD3uxrUCRxLqQKHg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM2N1NDA4azllWFJYY25N
            R2FVTUY5Rlh4dXlxVmh2bWtmRzFpdnF3SUI4CkFZUzRzSDdUSjJVVFJaWkFTZVNk
            YkdWSjdwQmU3cXdJdjQ4YWF6bWpJNVkKLS0tIFhsQVFKdTFsa3B3ZGZpQUliUDBF
            cG9LamZKN1hlWWhTT0wycllib0hJNkkK+/jDi9DwM6ou1LFqGhYjbsRdJcbnVBbR
            IJXQWDwYZsNyyAZn+jOBDQPKUTc9D9k2+uSMd0kqHbi0dUR+aHZfBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ly7h0vwxqjxffe78l3gp00lzue9g6m4w5w22e394q98umdk6wvxsynguxt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T07:10:15Z"
    mac: ENC[AES256_GCM,data:pKfAUTTOfnRVjQTdSoV5AFO0Cj3V83YxK61p2Bf7UxETFvxHZwhY2XQhn6drPatEgAantaJI3wbBljS5C+WKcPP13n00hye0enJSCNetEVq5TH3JHv4vmiCccJ1hr68R5tw7TvowZhDGntqBPrSOlgX/VgGolZbF07Wj7r+/kco=,iv:mS70NAvzT4sAu57hq/4NszR01XmvclTnoA8Q9mRdBLg=,tag:Qjem9RMkiye+HW/xgjnE4g==,type:str]
    version: 3.13.1
