apiVersion: v1
data:
    password: ENC[AES256_GCM,data:zMqUYY9uACdDcIWrJRCjGP11k7Q=,iv:XauSRtrBK6vUzMNw1on9xt6xIR9OxXkhGace89ay3Wo=,tag:ioDA1Q2dIA1mNHHYpCom2g==,type:str]
    user: ENC[AES256_GCM,data:O/K4JzVmFzk=,iv:YV6SScBzsxCHzw/S9RqQzmrVUxeg0jdd35pdJbh3WhU=,tag:iJO+hJ7qMrhK08qfadlobg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxN2ROWVMxaVdXQm9SV1FD
            T1R0cXRIVnh1TE1aNTBjZWhxTFNtRmxJdndrCnYxQUlZb25uMHFuY3hYdEtJS1U4
            NGl6UWw2ejlhZEN2VnpqSFlIVXVPL00KLS0tIExmVUtLKzlYcnNLQVNicXR4ZVhJ
            M1ZmSGtNbEpvalA1SXFQS1JPUkZ0VVkKb9IB1Iz2bGK6VHse2sj2Je5mtTISG987
            nUYHbRyKLJddkcxE6x6Q/ukIB2gZSW990A+txCpwmLTGsfQW6W48FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ly7h0vwxqjxffe78l3gp00lzue9g6m4w5w22e394q98umdk6wvxsynguxt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T09:11:16Z"
    mac: ENC[AES256_GCM,data:fgXTRU3O4euw80aoivdGqiB8rHEjMmEmParb3GSu8IQgwbtJ5eJEAnGTujd3ECly9YGyI6xSKxwdoX7HmzVrXtFfsmcJ5fdB5PsbEoFywSlLz8OVlCwuvZwzsgzxiMWlCgqsZutMjoWmZqoJwpBQttBlMqFVTJZAAEtKEwDmHHk=,iv:O7Ww5PLXoTPtTQ5fImOnuM1mEbHgVxX6nTqB8aRU7zk=,tag:9jlP8D1rkZ+PvkeQ7DUSRA==,type:str]
    version: 3.13.1
