apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:m6rx1k5ju7dmiL7T0dSsZNFyFCs=,iv:QmJDN+iePiYv7gijXBgRm3B88CsW0bxqPl91GFhuF0w=,tag:QUVmVlPgpI9dZEaBJNqB+A==,type:str]
    admin-user: ENC[AES256_GCM,data:YAu9+yySsVE=,iv:AaM2RYN1W117Yw9+JKIuIHGcBf4Oz3LRkBSAQhUWXmw=,tag:TrsiNZ9hMUIoTZnUWXahig==,type:str]
kind: Secret
metadata:
    name: grafana-password
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTnFhamRLbjlZSWN2cVda
            VE1qSTA3ZWNibU9UcjJBaW41dGN2Ny92OUZVCitaZi9yakx5T0FueVpFVVhtUFJZ
            anRKaVZyZTkxVGdkcDlxeEZNWUxFWGsKLS0tIGtnZStMcHZPN1VXZi9Fd3BMa0lk
            NndwUDhOTGN6TnNlRDd2U3RhalJhdTQKmhOCkyLrZGZV7onygeLyYyMcFEePjX5N
            sz/I7tDio88GdFYjsDq38PCUyUX6RYBL/FZ0xVnwOVCOvlfzYSjjpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ly7h0vwxqjxffe78l3gp00lzue9g6m4w5w22e394q98umdk6wvxsynguxt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T15:02:58Z"
    mac: ENC[AES256_GCM,data:kP60JtX/W5WYeEkZmR1jpLWWcPJabJZvU8tz/j5iaZrGzX6Kzb0PO6Ns4WfeMzKFoKWcowEMNWmf/zE7le2EunuKlVADK13wXiXubEIuPk9BcUG6/PrhkihM59vyUz2oxZ/1agCzg9xDACuyQHN4Tas7Ya9NQT3AhGmF1Ropk4o=,iv:QEty4BcX4tdee7Ku4ASaOeFO6+/ZYgEvx2fRKnmgtDQ=,tag:1WETkyjIXspYphwQG+Ku5g==,type:str]
    version: 3.13.1
